# Generated by Django 2.1.3 on 2019-02-26 15:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('release_time', models.DateField(auto_now_add=True)),
                ('show_pictures', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='展示图片')),
                ('visits', models.IntegerField(default=0, verbose_name='展示图片')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='Article_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '文章类型管理',
                'verbose_name_plural': '文章类型管理',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tpye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article_type', verbose_name='文章类型'),
        ),
    ]
