# Generated by Django 2.1.3 on 2019-02-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('about', models.CharField(max_length=200, verbose_name='主题描述')),
                ('theme_pictures', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='主题图片')),
            ],
            options={
                'verbose_name': '主题管理',
                'verbose_name_plural': '主题管理',
            },
        ),
    ]
